### ISSUE TITLE
現状の仕様と今後の整理

### ISSUE THREAD

**Issue by omuomugin** [HirokiFunami/mentors#1]
## WHY
機能の把握とエンドポイントの設計に必要。

### モデル周りの整理をする
1.モデルを1つのファイルにではなく、modelsパッケージ下にそれぞれのクラスで1つファイルを作る
2.モデルのリレーションの整理
 - [ ] CourseType必要？
 - [ ] 中間テーブルが多いので、実質リソースは、Mentor、Campus、Course、Camp

#### Mentor
- [ ] Mentorをユーザーとしてadminを作らないならロールが必要(owner, user)みたいに
- [ ] adminがいるなら問題ない
- [ ] 入れる情報は結構あるし、要検討

#### Campus
- [ ] official nameとuniversitiy nameの違い

### エンドポイントを議論する
ユースケースが決まりきってないけど、とりあえずリソースに関してはこんな感じ

- [ ] GET /mentors
- [ ] GET, POST, DELETE /mentor/:id
- [ ] GET /campuses
- [ ] GET, POST, DELETE /campuses/:id
- [ ] GET /courses
- [ ] GET, POST, DELETE /courses/:id
- [ ] GET /camp
- [ ] GET, POST, DELETE /camp/:id

今後写真とかも増えると思うからユースケースに応じてエンドポイントは当然増える

#### 未実装
- [ ] ギャラリー
  - [ ] googleフォトのリンクでやりとり
  - [ ] リソース的には、キャンプがhas_manyしてるのが正しそう

- [ ] マイページ
  - [ ] メンター情報が圧倒的に不足してるので、何を載せたら嬉しいか考える
  - [ ] 過去のキャンプ一覧、教えたメンバー数、Life is 何日目的なやつ

- [ ] プレビュー
  - [ ] UIが難しいところ

#### ジャストアイディア
- [ ] 勉強会、イベント情報など
  - [ ] google calendar連携すればいいのでは？

- [ ] メッセとかのSNSっぽさあると便利だね

**Comment by HirokiFunami** [comment]
楽しい

**Comment by HirokiFunami** [comment]
**CourseType必要？について！**
【作った理由】
メンターが次に学習したい、次に経験を積みたい、次にアンテナを張りたい、次に意識を向けたいコースを提示するのにコースの属性が重要なのかも！と思いつけていました。タグのような感覚です！
1,2コースしかやったことない、でも幅を広げたい、と考えているメンターに対して、そのメンターが見れるコースから考えてコースをオススメするじゃない？
例えば、キャンプ系のコースしかない人であれば、スクール系のコースを提示できるし、クリエイティブ系のコースであればアプリとかweb系のコースを提示できるかも！と！マイページで今の自分のコースから次に意識を向けて見れるといいコースとか見たいなあ、と！
【結論】
ただコースを分類するだけならいらないっす！リコメンドとかするなら必要な気がするっす！

**Comment by HirokiFunami** [comment]
**中間テーブルが多いので、実質リソースは、Mentor、Campus、Course、Camp**について！
【思うこと】
関連をhas_and_belongs_to_manyにしてモデルを減らせばよかったと作ってから思いまひた！

**Comment by omuomugin** [comment]
中間テーブルの話は、リソースの整理をしたかっただけ！中間テーブルはこれで正しいと思ってる。

**Comment by HirokiFunami** [comment]
うん！
has_and_belongs_to_manyにすると中間テーブルの**モデル**作んなくていいらしいってこと！

**Comment by omuomugin** [comment]
has_and_belongs_to_manyにすると中間テーブルのモデル作んなくていいらしいってこと！
これは、おそらく正しくないので中間テーブルがよい！

**Comment by HirokiFunami** [comment]
has_and_belongs_to_manyにすると中間テーブルのモデル作んなくていいらしいってこと！
これは、おそらく正しくないので中間テーブルがよい！
ん？中間テーブルは作るらしいぞ！中間テーブルのモデルを明示的に定義しなくて良いと読み取った！
https://railsguides.jp/association_basics.html#has-and-belongs-to-many%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91

確認しまふ！

**Comment by omuomugin** [comment]
ああ、じゃなくて

> ん？中間テーブルは作るらしいぞ！中間テーブルのモデルを明示的に定義しなくて良いと読み取った！

中間テーブルのモデルを定義しなくてもできるんだけど、モデルが増えることは別に悪いことではなくて、むしろbelongs_toとhas_many以外を多用すると他人がコードを読めなくなるからやらない方がいいっていう話！

「できる」と「すべき」は違う！

**Comment by omuomugin** [comment]
話遅くなったけど、CourseTypeってデザインとかプログラムってことか
これ、モデルじゃなくてCourseのattributeにenumで設定すればいい気がした。

**Comment by HirokiFunami** [comment]
>ああ、じゃなくて
>ん？中間テーブルは作るらしいぞ！中間テーブルのモデルを明示的に定義しなくて良いと読み取った！
中間テーブルのモデルを定義しなくてもできるんだけど、モデルが増えることは別に悪いことではなくて、むしろbelongs_toとhas_many以外を多用すると他人がコードを読めなくなるからやらない方がいいっていう話！
>「できる」と「すべき」は違う！

こちら理解しやした！Thanks！

**Comment by HirokiFunami** [comment]
>話遅くなったけど、CourseTypeってデザインとかプログラムってことか
これ、モデルじゃなくてCourseのattributeにenumで設定すればいい気がした。

あり！
