### ISSUE TITLE
開発面でやりたいこと

### ISSUE THREAD

**Issue by omuomugin** [HirokiFunami/mentors#2]
## WHY
開発面でいろいろ環境を整備したい

## WHAT
- [x] slackへの通知
- [x] master or developのオートデプロイ
- [ ] apiのドキュメント整理(swaggerとか)
- [x] 連絡手段の確保
- [ ] readmeを充実させて誰でも参加可能に
- [ ] 合宿

**Comment by HirokiFunami** [comment]
合宿熱いね！

**Comment by s11y** [comment]
合宿したいね
レビュー教育するなら、一緒にやったほうがいいし

コア機能の詰めとかapiの詰めとかはしたい

**Comment by HirokiFunami** [comment]
github連携テスト！

**Comment by HirokiFunami** [comment]
masterブランチのherokuへのオートデプロイ設定done
