### ISSUE TITLE
開発の全体感を決める

### ISSUE THREAD

**Issue by omuomugin** [HirokiFunami/mentors#3]
## WHY
今後何をどうやって開発していくか目処を立てるのは、大事

## WHAT
- [ ] コア機能決める
- [ ] api作成
  - [ ] ふなみんメイン
- [ ] デザイン画面
 - [ ] sketchとかxdとか
- [ ] クライアント開発
  - [ ] android 主にさぶうぇい
  - [ ] ios 主にしのきん
  - [ ] web 主にふなみん
- [ ] リリース
  - [ ] リリースは、ストアではなくクローズドで(個人情報の観点から)

開発面に関しては、学習の意味があった方が楽しいしいいかなと思ったから
- ふなみん -> web api
- さぶうぇいとしのきん -> iPhone、Androidコースを巻き込んでもよい。レビュー教育
- webのフロント -> ふなみん？webデザインチームとか？ツーブロやる？

**Comment by HirokiFunami** [comment]
webフロントもやりたいなあ！

**Comment by s11y** [comment]
巻き込もうか
Leaders for Schoolのだれか誘う

**Comment by HirokiFunami** [comment]
素晴らしデザイン作るならモック必要だなあ。XDかなあ！

**Comment by s11y** [comment]
XD正規版になったから、XD使いたいね

**Comment by omuomugin** [comment]
XD持ってないからなー、
でもいいと思いまーす。

ちなみに小言ですが
XDの不満点をあげるとすると、zepplinとかのデザイン共有サービスにあんま対応してなくて細かいpxとかが見れないところだ。

**Comment by s11y** [comment]
ライフイズテックが買ってくれてるなかに、XDって入ってないの？

**Comment by omuomugin** [comment]
それそもそも入れてないや笑
ccになってから面倒でインストールしてない笑

**Comment by s11y** [comment]
今つくって思ったけど、UIデザイナーほしさある

**Comment by HirokiFunami** [comment]
誰か巻き込むか。XD使える&デザインできる人がええな。

**Comment by HirokiFunami** [comment]
っていうシチュエーションでもMentorPreview使えるようにしたいな。

**Comment by s11y** [comment]
確かに！
デザインできるやつだれだーー

**Comment by HirokiFunami** [comment]
これみてて思ったんだけど
https://www.facebook.com/groups/1575278319432191/members/
ライフいいかもね。

**Comment by s11y** [comment]
ライフありやね
ふなみんから口説いてみてよ
