### ISSUE TITLE
地図上にキャンパスを中心に同心円にメンターのピンを表示

### ISSUE THREAD

**Issue by HirokiFunami** [HirokiFunami/mentors#6]
イメージ。ホバーするとメンターの情報がみれる。
<img width="521" alt="2017-10-17 12 12 02" src="https://user-images.githubusercontent.com/8609741/31645001-6e6c99c4-b334-11e7-889e-3c229f645050.png">

**Comment by omuomugin** [comment]
メンターのピンっていう概念がわかりづらいんだけど、これはメンターの何を指してるの？
その時に入ってたキャンプ？それとも現所在地？

**Comment by HirokiFunami** [comment]
その時入っていたキャンプ！キャンパスの位置をメンターの位置にすると大勢重なって見えないから、キャンパスを中心に同心円状に並べた方が面白いかな、と！

**Comment by omuomugin** [comment]
たしかに。なるほどね。
それかそもそもキャンプの場所にホバーしたらメンターが出てくるとかでも良さそうだけどね。
クライアントだとクリックしたらメンター一覧が見えるとか。

**Comment by HirokiFunami** [comment]
キャンプの場所にホバーしたらメンターが出てくる、も選択肢としてはあると思うし、そっちの方が便利な場合もあるはず！
ただ地図上でプレビューした時にメンターがたくさんいる感じを出したくて！
下の画像は極端だけど、こんな感じに！理想はメンターの画像。画像を扱うのがちょっとめんどくさそうと思い、一旦ピンでできたらなと！
![uploaded](https://user-images.githubusercontent.com/8609741/31647503-a4668b66-b343-11e7-8885-410158ed2ad5.jpg)

**Comment by HirokiFunami** [comment]
でけた。
<img width="864" alt="2017-10-18 1 24 11" src="https://user-images.githubusercontent.com/8609741/31676606-1f3cbe14-b3a3-11e7-8df4-89c02743602c.png">
各メンターの情報のうまい表示の仕方考えなきゃ！ホバーすると跳ねるといいね！
