### ISSUE TITLE
10/31までに作る機能

### ISSUE THREAD

**Issue by HirokiFunami** [HirokiFunami/mentors#7]
【MyPage】
面

【Preview】
- [ ] マップに動的に更新してピンの追加、ピンの削除を行えるように。
- [ ] 日付ボタンを作り、日付ごとに対応するキャンパス、メンター情報を表示できるように。

【Data】
- [ ] メンターに参加日数のデータを追加
- [x] キャンプに開催期間のデータを追加
- [ ] キャンパスの緯度経度を直打ちでなく、住所から入力できるように。
流れを考える必要あり。
【Gallary】
- [x] GooglePhotoのリンクを投稿&表示できるように。

10/31以降？
【全体】
レスポンシブ対応どうする？

Viewのコードを整理したい。動いていはいるがふなみ以外理解できないスパゲッティになってる。誰がみても動きがわかるようにしたい。
デザイン面をどうやって共有しましょうな？Xd作る前にフロントで実装してしまった方が気分的に楽ではあるが。モック作成->フロントに入っていくべきなんでしょうけども！作りたいなー！

コアバリュー、ユースケースなど話し合いたい。

apiを共有して、web、iOS、Androidでそれぞれが勝手に作り、議論しながら足並みを揃えるのがいいかな！担当が明確になるし、手柄も明確！web、iOS、Androidでそれぞれで使えるapiの整備が急務。

ベータ版をメンターに見せたい。
少し自分の情報いじれる。

入力してもらったデータってどこにバックアップとか取ればいいんだ？

**Comment by s11y** [comment]
API共有したい。
とりあえずAndroidとユースケースと導線・コア機能決めて、ほしいAPIを指定したほうがいい？

MyPageがあってログインがあるなら、そこはクライアント側でまずつくれるから、ログインのAPIほしいな

**Comment by HirokiFunami** [comment]
ログインのAPIね！やってみる！
ふつうにデータ返したり、追加したりするapiも実装しやす！

**Comment by HirokiFunami** [comment]
[11/1~11/7の開発方針](https://github.com/MentorPreview/MentorPreview-web/issues/13)
に引き継ぎ
